// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string):Promise<Array<main.Todo>>;

export function DeleteTodo(arg1:string):Promise<Array<main.Todo>>;

export function EditTodo(arg1:string,arg2:string):Promise<Array<main.Todo>>;

export function GetTodos():Promise<Array<main.Todo>>;

export function ToggleTodo(arg1:string):Promise<Array<main.Todo>>;
